### ISSUE TITLE
Flashing bars

### ISSUE THREAD

**Issue by MarcoLeder** [mp-access/Frontend#50]
chrome, windows 10

https://youtu.be/OarE2BpIRec

Flashing bars

**Comment by a-a-hofmann** [comment]
Hi @MarcoLeder 
Thanks for the issue report!
Unfortunately the video is set to private instead of unlisted so we can't see it

**Comment by MarcoLeder** [comment]
ACCESS.webm
<https://drive.google.com/file/d/1z4cePkqd3m_19C_JqpTMN6t4ltVKyER2/view?usp=drive_web>


Am Do., 26. Sept. 2019 um 10:57 Uhr schrieb a-a-hofmann <
notifications@github.com>:

**Comment by Haeri** [comment]
Hi there
Yesterday we pushed out a new frontend update, which adressed the issue with the scrollbars. Can you check again if the issue is fixed for you now?

**Comment by MarcoLeder** [comment]
Yes, looks fine now - thank you

Am Do., 17. Okt. 2019 um 14:28 Uhr schrieb Haeri <notifications@github.com>:
