### ISSUE TITLE
Navigation backwards button

### ISSUE THREAD

**Issue by flobachofner** [mp-access/Frontend#54]
The navigation between exercises would be much easier with a backward button included! :)

**Comment by Haeri** [comment]
Hi there!

Thank you for opening the issue. We have just merged the fix for this into our dev branch here:
- https://github.com/mp-access/Frontend/pull/58
- https://github.com/mp-access/Backend/pull/336

If everything goes well, you will see it in the next release 😀

Best regards
Haeri
